### ISSUE TITLE
not downloading just restart prompts

### ISSUE THREAD

**Issue by prodojaye** [insaiyancvk/music_downloader#2]
![Screenshot 2021-03-23 230813](https://user-images.githubusercontent.com/81276878/112248703-c49ceb80-8c2c-11eb-9c46-d747815a7150.png)

**Comment by insaiyancvk** [comment]
Hey, @prodojaye it looks like you entered a URI that doesn't exist.

![image](https://user-images.githubusercontent.com/53230977/112253631-140f0600-8c85-11eb-982d-cfc0b3458a30.png)

I Will add a prompt message in the next patch.
